name: 'inno-setup-action'
description: 'Generate setup files using Inno Setup'

inputs:
  filepath:
    description: 'Path to ISS file'
    required: true

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}\src\ISCC.exe ${{inputs.filepath}}
      shell: cmd
